# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink: /:year/:month/:day/:title/

# Setup
title:            Friendly-Invention
tagline:          "Friendly Things"
description:      'Words and things by Sabarish.'
baseurl:          /

author:
  name:           "Sabarish Santhoshkumar"
  url:            https://friendly-invention.github.io/
  twitter:        

plugins:
    - jekyll-paginate
    - jekyll-redirect-from
