# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink: /:year/:month/:day/:title/

# Setup
title:            Friendly-Invention
tagline:          "Things by Nick O'Leary"
description:      'Words and things by Sabarish.'
baseurl:          /

author:
  name:           "Sabarish Santhoshkumar"
  url:            https://twitter.com/knolleary
  twitter:        "@knolleary"

plugins:
    - jekyll-paginate
    - jekyll-redirect-from
